### ISSUE TITLE
Seesaw Address is set to non-default value in mrfconstants.h

### ISSUE THREAD

**Issue by masonjar3883** [acornelissen/IDENTIDEM.design-MRF#10]
While doing some initial checkouts, I noted my MRF seemed to be stuck in a reboot loop.  After some troubleshooting, I narrowed the issue down to the Seesaw I2C address as defined in mrfconstants.h.  The current value is set a non-default address (0x38) which is for a configuration with the A1 jumper closed on the Seesaw encoder.  I set the value back to the default (0x36 - no jumpers closed), which resolved my issue.

Suggest others may benefit from a comment in the code / build guide referencing the Adafruit pinout information (https://learn.adafruit.com/adafruit-i2c-qt-rotary-encoder/pinouts), or perhaps a note in the build instructions to close jumper A1 on their Seesaw Encoders if they do not wish to modify the I2C address in the code.

Other than that, the build guide and the firmware have been fantastic!

**Comment by acornelissen** [comment]
@masonjar3883 ah, good catch! I think easiest would just be to set this back to the default in the code, which I've done. 
I had a bad batch and had tried everything to to get them to work, I guess this was just a holdover from that. 

I'm super happy to hear the build's going well. I'd love to see the pictures you eventually make with the MRF - so please pop over a place I can see your photos if you don't mind sharing!
