### ISSUE TITLE
No variations for beam splitter plate in 1.2mm thickness

### ISSUE THREAD

**Issue by siawyoung** [acornelissen/IDENTIDEM.design-MRF#6]
Hi, I'm accessing the link for plate beam splitter but it doesn't seem like they make it in 1.2mm thickness (or maybe it's not available anymore). Is 1.1mm ok?

https://www.ebay.co.uk/itm/225028201670

<img width="470" alt="image" src="https://github.com/acornelissen/IDENTIDEM.design-MRF/assets/4199642/41b4b05c-347c-4b66-9457-710718b1f485">

**Comment by acornelissen** [comment]
@siawyoung that's a typo on my end, thanks for pointing it out! 1.1mm is perfect. I'll fix the BoM.
